<?php
    //Example1
     //<script>
     //      require(['jquery'], function () {
        //    require(['LearnMagento_CarouselWidget/js/carousel/owl.carousel.min']);
      //});

      //</script>

 //<script src="<?= $block->escapeUrl($block->getViewFileUrl('LearnMagento_CarouselWidget::js/carousel/owl.carousel.min.js')); ?"></script>

?>



<!--Example 3:-->
<script type="text/x-magento-init">
    {
         "*": {
             "LearnMagento_CarouselWidget/js/carousel/": {}
         }
    }


</script>




